/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SxVault9k2m7xRouteImport } from './routes/sx-vault-9k2m7x'
import { Route as SizeGuideRouteImport } from './routes/size-guide'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as ManifestDotjsonRouteImport } from './routes/manifest[.]json'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated/withdraw'
import { Route as AuthenticatedUpgradeRouteImport } from './routes/_authenticated/upgrade'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedStatisticsRouteImport } from './routes/_authenticated/statistics'
import { Route as AuthenticatedSmartFilterRouteImport } from './routes/_authenticated/smart-filter'
import { Route as AuthenticatedNoticesRouteImport } from './routes/_authenticated/notices'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedLinkDebuggerRouteImport } from './routes/_authenticated/link-debugger'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedDomainsRouteImport } from './routes/_authenticated/domains'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedControlPanelRouteImport } from './routes/_authenticated/control-panel'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as ApiPublicSafePoolRefreshRouteImport } from './routes/api/public/safe-pool-refresh'
import { Route as ApiPublicPlisioWebhookRouteImport } from './routes/api/public/plisio-webhook'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicPreviewPrelandingCodeRouteImport } from './routes/api/public/preview-prelanding.$code'
import { Route as ApiPublicHooksMetaCrawlerProbeRouteImport } from './routes/api/public/hooks/meta-crawler-probe'
import { Route as ApiPublicHooksLeakScanRouteImport } from './routes/api/public/hooks/leak-scan'
import { Route as ApiPublicHooksDomainHealthScanRouteImport } from './routes/api/public/hooks/domain-health-scan'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SxVault9k2m7xRoute = SxVault9k2m7xRouteImport.update({
  id: '/sx-vault-9k2m7x',
  path: '/sx-vault-9k2m7x',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeGuideRoute = SizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotjsonRoute = ManifestDotjsonRouteImport.update({
  id: '/manifest.json',
  path: '/manifest.json',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUpgradeRoute = AuthenticatedUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatisticsRoute = AuthenticatedStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSmartFilterRoute =
  AuthenticatedSmartFilterRouteImport.update({
    id: '/smart-filter',
    path: '/smart-filter',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNoticesRoute = AuthenticatedNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLinkDebuggerRoute =
  AuthenticatedLinkDebuggerRouteImport.update({
    id: '/link-debugger',
    path: '/link-debugger',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDomainsRoute = AuthenticatedDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedControlPanelRoute =
  AuthenticatedControlPanelRouteImport.update({
    id: '/control-panel',
    path: '/control-panel',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicSafePoolRefreshRoute =
  ApiPublicSafePoolRefreshRouteImport.update({
    id: '/api/public/safe-pool-refresh',
    path: '/api/public/safe-pool-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPlisioWebhookRoute = ApiPublicPlisioWebhookRouteImport.update({
  id: '/api/public/plisio-webhook',
  path: '/api/public/plisio-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPreviewPrelandingCodeRoute =
  ApiPublicPreviewPrelandingCodeRouteImport.update({
    id: '/api/public/preview-prelanding/$code',
    path: '/api/public/preview-prelanding/$code',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMetaCrawlerProbeRoute =
  ApiPublicHooksMetaCrawlerProbeRouteImport.update({
    id: '/api/public/hooks/meta-crawler-probe',
    path: '/api/public/hooks/meta-crawler-probe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLeakScanRoute = ApiPublicHooksLeakScanRouteImport.update({
  id: '/api/public/hooks/leak-scan',
  path: '/api/public/hooks/leak-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDomainHealthScanRoute =
  ApiPublicHooksDomainHealthScanRouteImport.update({
    id: '/api/public/hooks/domain-health-scan',
    path: '/api/public/hooks/domain-health-scan',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/size-guide': typeof SizeGuideRoute
  '/sx-vault-9k2m7x': typeof SxVault9k2m7xRoute
  '/terms': typeof TermsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/control-panel': typeof AuthenticatedControlPanelRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/domains': typeof AuthenticatedDomainsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/link-debugger': typeof AuthenticatedLinkDebuggerRoute
  '/live': typeof AuthenticatedLiveRoute
  '/notices': typeof AuthenticatedNoticesRoute
  '/smart-filter': typeof AuthenticatedSmartFilterRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/r/$code': typeof RCodeRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/plisio-webhook': typeof ApiPublicPlisioWebhookRoute
  '/api/public/safe-pool-refresh': typeof ApiPublicSafePoolRefreshRoute
  '/api/public/hooks/domain-health-scan': typeof ApiPublicHooksDomainHealthScanRoute
  '/api/public/hooks/leak-scan': typeof ApiPublicHooksLeakScanRoute
  '/api/public/hooks/meta-crawler-probe': typeof ApiPublicHooksMetaCrawlerProbeRoute
  '/api/public/preview-prelanding/$code': typeof ApiPublicPreviewPrelandingCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/size-guide': typeof SizeGuideRoute
  '/sx-vault-9k2m7x': typeof SxVault9k2m7xRoute
  '/terms': typeof TermsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/control-panel': typeof AuthenticatedControlPanelRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/domains': typeof AuthenticatedDomainsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/link-debugger': typeof AuthenticatedLinkDebuggerRoute
  '/live': typeof AuthenticatedLiveRoute
  '/notices': typeof AuthenticatedNoticesRoute
  '/smart-filter': typeof AuthenticatedSmartFilterRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/r/$code': typeof RCodeRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/blog': typeof BlogIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/plisio-webhook': typeof ApiPublicPlisioWebhookRoute
  '/api/public/safe-pool-refresh': typeof ApiPublicSafePoolRefreshRoute
  '/api/public/hooks/domain-health-scan': typeof ApiPublicHooksDomainHealthScanRoute
  '/api/public/hooks/leak-scan': typeof ApiPublicHooksLeakScanRoute
  '/api/public/hooks/meta-crawler-probe': typeof ApiPublicHooksMetaCrawlerProbeRoute
  '/api/public/preview-prelanding/$code': typeof ApiPublicPreviewPrelandingCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/size-guide': typeof SizeGuideRoute
  '/sx-vault-9k2m7x': typeof SxVault9k2m7xRoute
  '/terms': typeof TermsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/control-panel': typeof AuthenticatedControlPanelRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/domains': typeof AuthenticatedDomainsRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/link-debugger': typeof AuthenticatedLinkDebuggerRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/notices': typeof AuthenticatedNoticesRoute
  '/_authenticated/smart-filter': typeof AuthenticatedSmartFilterRoute
  '/_authenticated/statistics': typeof AuthenticatedStatisticsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/upgrade': typeof AuthenticatedUpgradeRoute
  '/_authenticated/withdraw': typeof AuthenticatedWithdrawRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/r/$code': typeof RCodeRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/plisio-webhook': typeof ApiPublicPlisioWebhookRoute
  '/api/public/safe-pool-refresh': typeof ApiPublicSafePoolRefreshRoute
  '/api/public/hooks/domain-health-scan': typeof ApiPublicHooksDomainHealthScanRoute
  '/api/public/hooks/leak-scan': typeof ApiPublicHooksLeakScanRoute
  '/api/public/hooks/meta-crawler-probe': typeof ApiPublicHooksMetaCrawlerProbeRoute
  '/api/public/preview-prelanding/$code': typeof ApiPublicPreviewPrelandingCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/llms.txt'
    | '/login'
    | '/manifest.json'
    | '/order-confirmed'
    | '/pricing'
    | '/privacy'
    | '/returns'
    | '/robots.txt'
    | '/shipping'
    | '/shop'
    | '/signup'
    | '/sitemap.xml'
    | '/size-guide'
    | '/sx-vault-9k2m7x'
    | '/terms'
    | '/analytics'
    | '/control-panel'
    | '/dashboard'
    | '/domains'
    | '/leaderboard'
    | '/link-debugger'
    | '/live'
    | '/notices'
    | '/smart-filter'
    | '/statistics'
    | '/support'
    | '/upgrade'
    | '/withdraw'
    | '/blog/$slug'
    | '/r/$code'
    | '/shop/$slug'
    | '/blog/'
    | '/api/public/health'
    | '/api/public/plisio-webhook'
    | '/api/public/safe-pool-refresh'
    | '/api/public/hooks/domain-health-scan'
    | '/api/public/hooks/leak-scan'
    | '/api/public/hooks/meta-crawler-probe'
    | '/api/public/preview-prelanding/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/llms.txt'
    | '/login'
    | '/manifest.json'
    | '/order-confirmed'
    | '/pricing'
    | '/privacy'
    | '/returns'
    | '/robots.txt'
    | '/shipping'
    | '/shop'
    | '/signup'
    | '/sitemap.xml'
    | '/size-guide'
    | '/sx-vault-9k2m7x'
    | '/terms'
    | '/analytics'
    | '/control-panel'
    | '/dashboard'
    | '/domains'
    | '/leaderboard'
    | '/link-debugger'
    | '/live'
    | '/notices'
    | '/smart-filter'
    | '/statistics'
    | '/support'
    | '/upgrade'
    | '/withdraw'
    | '/blog/$slug'
    | '/r/$code'
    | '/shop/$slug'
    | '/blog'
    | '/api/public/health'
    | '/api/public/plisio-webhook'
    | '/api/public/safe-pool-refresh'
    | '/api/public/hooks/domain-health-scan'
    | '/api/public/hooks/leak-scan'
    | '/api/public/hooks/meta-crawler-probe'
    | '/api/public/preview-prelanding/$code'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/llms.txt'
    | '/login'
    | '/manifest.json'
    | '/order-confirmed'
    | '/pricing'
    | '/privacy'
    | '/returns'
    | '/robots.txt'
    | '/shipping'
    | '/shop'
    | '/signup'
    | '/sitemap.xml'
    | '/size-guide'
    | '/sx-vault-9k2m7x'
    | '/terms'
    | '/_authenticated/analytics'
    | '/_authenticated/control-panel'
    | '/_authenticated/dashboard'
    | '/_authenticated/domains'
    | '/_authenticated/leaderboard'
    | '/_authenticated/link-debugger'
    | '/_authenticated/live'
    | '/_authenticated/notices'
    | '/_authenticated/smart-filter'
    | '/_authenticated/statistics'
    | '/_authenticated/support'
    | '/_authenticated/upgrade'
    | '/_authenticated/withdraw'
    | '/blog/$slug'
    | '/r/$code'
    | '/shop/$slug'
    | '/blog/'
    | '/api/public/health'
    | '/api/public/plisio-webhook'
    | '/api/public/safe-pool-refresh'
    | '/api/public/hooks/domain-health-scan'
    | '/api/public/hooks/leak-scan'
    | '/api/public/hooks/meta-crawler-probe'
    | '/api/public/preview-prelanding/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  ManifestDotjsonRoute: typeof ManifestDotjsonRoute
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRouteWithChildren
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SizeGuideRoute: typeof SizeGuideRoute
  SxVault9k2m7xRoute: typeof SxVault9k2m7xRoute
  TermsRoute: typeof TermsRoute
  RCodeRoute: typeof RCodeRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicPlisioWebhookRoute: typeof ApiPublicPlisioWebhookRoute
  ApiPublicSafePoolRefreshRoute: typeof ApiPublicSafePoolRefreshRoute
  ApiPublicHooksDomainHealthScanRoute: typeof ApiPublicHooksDomainHealthScanRoute
  ApiPublicHooksLeakScanRoute: typeof ApiPublicHooksLeakScanRoute
  ApiPublicHooksMetaCrawlerProbeRoute: typeof ApiPublicHooksMetaCrawlerProbeRoute
  ApiPublicPreviewPrelandingCodeRoute: typeof ApiPublicPreviewPrelandingCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sx-vault-9k2m7x': {
      id: '/sx-vault-9k2m7x'
      path: '/sx-vault-9k2m7x'
      fullPath: '/sx-vault-9k2m7x'
      preLoaderRoute: typeof SxVault9k2m7xRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size-guide': {
      id: '/size-guide'
      path: '/size-guide'
      fullPath: '/size-guide'
      preLoaderRoute: typeof SizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.json': {
      id: '/manifest.json'
      path: '/manifest.json'
      fullPath: '/manifest.json'
      preLoaderRoute: typeof ManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AuthenticatedWithdrawRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/upgrade': {
      id: '/_authenticated/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AuthenticatedUpgradeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/statistics': {
      id: '/_authenticated/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AuthenticatedStatisticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/smart-filter': {
      id: '/_authenticated/smart-filter'
      path: '/smart-filter'
      fullPath: '/smart-filter'
      preLoaderRoute: typeof AuthenticatedSmartFilterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notices': {
      id: '/_authenticated/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof AuthenticatedNoticesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/link-debugger': {
      id: '/_authenticated/link-debugger'
      path: '/link-debugger'
      fullPath: '/link-debugger'
      preLoaderRoute: typeof AuthenticatedLinkDebuggerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/domains': {
      id: '/_authenticated/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AuthenticatedDomainsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/control-panel': {
      id: '/_authenticated/control-panel'
      path: '/control-panel'
      fullPath: '/control-panel'
      preLoaderRoute: typeof AuthenticatedControlPanelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/safe-pool-refresh': {
      id: '/api/public/safe-pool-refresh'
      path: '/api/public/safe-pool-refresh'
      fullPath: '/api/public/safe-pool-refresh'
      preLoaderRoute: typeof ApiPublicSafePoolRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plisio-webhook': {
      id: '/api/public/plisio-webhook'
      path: '/api/public/plisio-webhook'
      fullPath: '/api/public/plisio-webhook'
      preLoaderRoute: typeof ApiPublicPlisioWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/preview-prelanding/$code': {
      id: '/api/public/preview-prelanding/$code'
      path: '/api/public/preview-prelanding/$code'
      fullPath: '/api/public/preview-prelanding/$code'
      preLoaderRoute: typeof ApiPublicPreviewPrelandingCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/meta-crawler-probe': {
      id: '/api/public/hooks/meta-crawler-probe'
      path: '/api/public/hooks/meta-crawler-probe'
      fullPath: '/api/public/hooks/meta-crawler-probe'
      preLoaderRoute: typeof ApiPublicHooksMetaCrawlerProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/leak-scan': {
      id: '/api/public/hooks/leak-scan'
      path: '/api/public/hooks/leak-scan'
      fullPath: '/api/public/hooks/leak-scan'
      preLoaderRoute: typeof ApiPublicHooksLeakScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/domain-health-scan': {
      id: '/api/public/hooks/domain-health-scan'
      path: '/api/public/hooks/domain-health-scan'
      fullPath: '/api/public/hooks/domain-health-scan'
      preLoaderRoute: typeof ApiPublicHooksDomainHealthScanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedControlPanelRoute: typeof AuthenticatedControlPanelRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDomainsRoute: typeof AuthenticatedDomainsRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedLinkDebuggerRoute: typeof AuthenticatedLinkDebuggerRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedNoticesRoute: typeof AuthenticatedNoticesRoute
  AuthenticatedSmartFilterRoute: typeof AuthenticatedSmartFilterRoute
  AuthenticatedStatisticsRoute: typeof AuthenticatedStatisticsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedUpgradeRoute: typeof AuthenticatedUpgradeRoute
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedControlPanelRoute: AuthenticatedControlPanelRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDomainsRoute: AuthenticatedDomainsRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedLinkDebuggerRoute: AuthenticatedLinkDebuggerRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedNoticesRoute: AuthenticatedNoticesRoute,
  AuthenticatedSmartFilterRoute: AuthenticatedSmartFilterRoute,
  AuthenticatedStatisticsRoute: AuthenticatedStatisticsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedUpgradeRoute: AuthenticatedUpgradeRoute,
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  ManifestDotjsonRoute: ManifestDotjsonRoute,
  OrderConfirmedRoute: OrderConfirmedRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRouteWithChildren,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SizeGuideRoute: SizeGuideRoute,
  SxVault9k2m7xRoute: SxVault9k2m7xRoute,
  TermsRoute: TermsRoute,
  RCodeRoute: RCodeRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicPlisioWebhookRoute: ApiPublicPlisioWebhookRoute,
  ApiPublicSafePoolRefreshRoute: ApiPublicSafePoolRefreshRoute,
  ApiPublicHooksDomainHealthScanRoute: ApiPublicHooksDomainHealthScanRoute,
  ApiPublicHooksLeakScanRoute: ApiPublicHooksLeakScanRoute,
  ApiPublicHooksMetaCrawlerProbeRoute: ApiPublicHooksMetaCrawlerProbeRoute,
  ApiPublicPreviewPrelandingCodeRoute: ApiPublicPreviewPrelandingCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
